"""
GitHub PR creator for Cloud Cost Optimizer.

Automates the entire code-to-PR pipeline:
1. Creates a feature branch ``cost-opt/{service}-{resource_id}``
2. Commits the Claude-generated Terraform HCL
3. Opens a pull request with a structured body

Uses PyGithub for all GitHub interactions.

Usage
-----
    from actions.github_pr import create_optimization_pr
    pr_url = create_optimization_pr(recommendation)
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone

from github import Github, GithubException

from config.settings import settings
from detect.models import Recommendation

logger = logging.getLogger(__name__)


# ──────────────────────────────────────────────────────────────────────────────
# PR Body Template
# ──────────────────────────────────────────────────────────────────────────────

_PR_BODY_TEMPLATE = """\
## 💰 Cloud Cost Optimization

**Auto-generated by Cloud Cost Optimizer**

### Anomaly Summary

| Field | Value |
|-------|-------|
| **Service** | {service} |
| **Resource** | `{resource_id}` |
| **Issue Type** | {issue_type} |
| **Current Cost** | ${current_cost:.2f}/month |
| **Expected Cost** | ${expected_cost:.2f}/month |
| **Waste Score** | {waste_score}/100 |
| **Region** | {region} |

### 🔍 Root Cause

{root_cause}

### ✅ Recommended Actions

{actions_list}

### 💵 Savings Estimate

**${savings_estimate:.2f}/month** (${annual_savings:.2f}/year)

### ⚠️ Risk Level: {risk_level}

### 🔄 Rollback Plan

{rollback_plan}

---

> **Confidence:** {confidence:.0%}
>
> ⚡ This PR was automatically generated. Please review the Terraform changes carefully before merging.
"""


# ──────────────────────────────────────────────────────────────────────────────
# GitHub Operations
# ──────────────────────────────────────────────────────────────────────────────


def _sanitize_branch_name(name: str) -> str:
    """Sanitize a string for use in a Git branch name."""
    sanitized = re.sub(r"[^a-zA-Z0-9_-]", "-", name)
    return sanitized.strip("-").lower()[:60]


def create_optimization_pr(recommendation: Recommendation) -> str:
    """
    Create a GitHub pull request with the optimization Terraform code.
    (MOCKED FOR DEMO VERSION)
    """
    anomaly = recommendation.anomaly

    # Create branch name
    resource_part = _sanitize_branch_name(anomaly.resource_id or anomaly.issue_type.value)
    service_part = _sanitize_branch_name(anomaly.service)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M")
    branch_name = f"cost-opt/{service_part}-{resource_part}-{timestamp}"

    logger.info("Mock: Creating branch: %s", branch_name)
    logger.info("Mock: Committed terraform to branch %s", branch_name)
    
    pr_url = f"https://github.com/mock-org/mock-repo/pull/999"
    logger.info("Mock: Created PR: %s", pr_url)
    return pr_url
