"""
GitHub PR creator for Cloud Cost Optimizer.

Automates the entire code-to-PR pipeline:
1. Creates a feature branch ``cost-opt/{service}-{resource_id}``
2. Commits the Claude-generated Terraform HCL
3. Opens a pull request with a structured body

Uses PyGithub for all GitHub interactions.

Usage
-----
    from actions.github_pr import create_optimization_pr
    pr_url = create_optimization_pr(recommendation)
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone

from github import Github, GithubException

from config.settings import settings
from detect.models import Recommendation

logger = logging.getLogger(__name__)


# ──────────────────────────────────────────────────────────────────────────────
# PR Body Template
# ──────────────────────────────────────────────────────────────────────────────

_PR_BODY_TEMPLATE = """\
## 💰 Cloud Cost Optimization

**Auto-generated by Cloud Cost Optimizer**

### Anomaly Summary

| Field | Value |
|-------|-------|
| **Service** | {service} |
| **Resource** | `{resource_id}` |
| **Issue Type** | {issue_type} |
| **Current Cost** | ${current_cost:.2f}/month |
| **Expected Cost** | ${expected_cost:.2f}/month |
| **Waste Score** | {waste_score}/100 |
| **Region** | {region} |

### 🔍 Root Cause

{root_cause}

### ✅ Recommended Actions

{actions_list}

### 💵 Savings Estimate

**${savings_estimate:.2f}/month** (${annual_savings:.2f}/year)

### ⚠️ Risk Level: {risk_level}

### 🔄 Rollback Plan

{rollback_plan}

---

> **Confidence:** {confidence:.0%}
>
> ⚡ This PR was automatically generated. Please review the Terraform changes carefully before merging.
"""


# ──────────────────────────────────────────────────────────────────────────────
# GitHub Operations
# ──────────────────────────────────────────────────────────────────────────────


def _sanitize_branch_name(name: str) -> str:
    """Sanitize a string for use in a Git branch name."""
    sanitized = re.sub(r"[^a-zA-Z0-9_-]", "-", name)
    return sanitized.strip("-").lower()[:60]


def create_optimization_pr(recommendation: Recommendation) -> str:
    """
    Create a GitHub pull request with the optimization Terraform code.

    Steps
    -----
    1. Connect to the target GitHub repo.
    2. Create a new branch from main/master.
    3. Commit the Terraform HCL to the appropriate file path.
    4. Open a pull request with a detailed body.

    Parameters
    ----------
    recommendation : Recommendation
        The full recommendation including Terraform code and anomaly data.

    Returns
    -------
    str
        The URL of the created pull request.

    Raises
    ------
    GithubException
        If any GitHub API call fails.
    """
    anomaly = recommendation.anomaly
    g = Github(settings.GITHUB_TOKEN)

    try:
        repo = g.get_repo(settings.GITHUB_REPO)
    except GithubException as exc:
        logger.error("Failed to access repo %s: %s", settings.GITHUB_REPO, exc)
        raise

    # Determine base branch (prefer 'main', fall back to 'master')
    try:
        base_branch = repo.get_branch("main")
        base_ref = "main"
    except GithubException:
        base_branch = repo.get_branch("master")
        base_ref = "master"

    # Create branch name
    resource_part = _sanitize_branch_name(anomaly.resource_id or anomaly.issue_type.value)
    service_part = _sanitize_branch_name(anomaly.service)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M")
    branch_name = f"cost-opt/{service_part}-{resource_part}-{timestamp}"

    logger.info("Creating branch: %s", branch_name)

    # Create the branch
    repo.create_git_ref(
        ref=f"refs/heads/{branch_name}",
        sha=base_branch.commit.sha,
    )

    # Determine the file path for the Terraform code
    file_path = f"terraform/{service_part}_optimization/{resource_part}.tf"

    # Commit the Terraform file
    commit_message = (
        f"chore(cost-opt): {anomaly.issue_type.value} fix for {anomaly.service}\n\n"
        f"Estimated savings: ${recommendation.savings_estimate:.2f}/month\n"
        f"Risk level: {recommendation.risk_level.value}\n"
        f"Resource: {anomaly.resource_id or 'N/A'}\n\n"
        f"Auto-generated by Cloud Cost Optimizer"
    )

    repo.create_file(
        path=file_path,
        message=commit_message,
        content=recommendation.terraform_code,
        branch=branch_name,
    )

    logger.info("Committed %s to branch %s", file_path, branch_name)

    # Build PR body
    actions_list = "\n".join(
        f"{i}. {action}" for i, action in enumerate(recommendation.actions, 1)
    )

    pr_body = _PR_BODY_TEMPLATE.format(
        service=anomaly.service,
        resource_id=anomaly.resource_id or "N/A",
        issue_type=anomaly.issue_type.value,
        current_cost=anomaly.current_cost,
        expected_cost=anomaly.expected_cost,
        waste_score=anomaly.waste_score,
        region=anomaly.region or settings.AWS_DEFAULT_REGION,
        root_cause=recommendation.root_cause,
        actions_list=actions_list or "No specific actions listed.",
        savings_estimate=recommendation.savings_estimate,
        annual_savings=recommendation.savings_estimate * 12,
        risk_level=recommendation.risk_level.value.upper(),
        rollback_plan=recommendation.rollback_plan,
        confidence=recommendation.confidence,
    )

    # Create pull request
    pr_title = (
        f"💰 [{anomaly.service}] {anomaly.issue_type.value}: "
        f"Save ${recommendation.savings_estimate:.0f}/mo"
    )

    pr = repo.create_pull(
        title=pr_title,
        body=pr_body,
        head=branch_name,
        base=base_ref,
    )

    # Add labels if they exist
    try:
        pr.add_to_labels("cost-optimization", "auto-generated")
    except GithubException:
        logger.debug("Labels not available, skipping")

    logger.info("Created PR #%d: %s", pr.number, pr.html_url)
    return pr.html_url
