"""
Slack notification sender for Cloud Cost Optimizer.

Posts structured messages to a Slack incoming webhook with details about
detected anomalies, recommended actions, savings estimates, and PR links.

Usage
-----
    from actions.slack_notify import send_notification
    send_notification(anomaly, recommendation, pr_url)
"""

from __future__ import annotations

import json
import logging

import requests

from config.settings import settings
from detect.models import Anomaly, Recommendation

logger = logging.getLogger(__name__)


# ──────────────────────────────────────────────────────────────────────────────
# Slack Message Formatting
# ──────────────────────────────────────────────────────────────────────────────

_RISK_EMOJI = {
    "low": "🟢",
    "medium": "🟡",
    "high": "🔴",
}

_ISSUE_EMOJI = {
    "cost_spike": "📈",
    "idle_resource": "😴",
    "overprovisioned": "🐘",
    "stopped_but_billed": "⏸️",
    "waste_pattern": "🗑️",
}


def _build_slack_blocks(
    anomaly: Anomaly,
    recommendation: Recommendation,
    pr_url: str,
) -> list[dict]:
    """
    Build Slack Block Kit blocks for a rich notification message.
    """
    issue_emoji = _ISSUE_EMOJI.get(anomaly.issue_type.value, "⚠️")
    risk_emoji = _RISK_EMOJI.get(recommendation.risk_level.value, "⚪")

    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"💰 Cost Optimization Detected — {anomaly.service}",
                "emoji": True,
            },
        },
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"*Service:*\n{anomaly.service}",
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Issue Type:*\n{issue_emoji} {anomaly.issue_type.value}",
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Current Cost:*\n${anomaly.current_cost:.2f}/mo",
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Waste Score:*\n{anomaly.waste_score}/100",
                },
            ],
        },
        {"type": "divider"},
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"*Root Cause:*\n{recommendation.root_cause[:300]}\n\n"
                    f"*Estimated Savings:* 💵 *${recommendation.savings_estimate:.2f}/month* "
                    f"(${recommendation.savings_estimate * 12:.2f}/year)\n\n"
                    f"*Risk Level:* {risk_emoji} {recommendation.risk_level.value.upper()}"
                ),
            },
        },
    ]

    # Add resource details if available
    if anomaly.resource_id:
        blocks.append(
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Resource:* `{anomaly.resource_id}` | *Region:* {anomaly.region or 'N/A'}",
                },
            }
        )

    # Add actions
    if recommendation.actions:
        actions_text = "\n".join(
            f"• {action}" for action in recommendation.actions[:5]
        )
        blocks.append(
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Recommended Actions:*\n{actions_text}",
                },
            }
        )

    # Add PR link button
    if pr_url:
        blocks.extend([
            {"type": "divider"},
            {
                "type": "actions",
                "elements": [
                    {
                        "type": "button",
                        "text": {
                            "type": "plain_text",
                            "text": "📋 Review Pull Request",
                            "emoji": True,
                        },
                        "url": pr_url,
                        "style": "primary",
                    },
                ],
            },
        ])

    # Footer
    blocks.append(
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": "🤖 Auto-generated by *Cloud Cost Optimizer* | "
                    f"Confidence: {recommendation.confidence:.0%}",
                },
            ],
        }
    )

    return blocks


# ──────────────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────────────


def send_notification(
    anomaly: Anomaly,
    recommendation: Recommendation,
    pr_url: str = "",
) -> bool:
    """
    Send a Slack notification about a cost optimization opportunity.

    Parameters
    ----------
    anomaly : Anomaly
        The detected anomaly.
    recommendation : Recommendation
        The Claude-generated recommendation.
    pr_url : str
        URL of the created pull request (optional).

    Returns
    -------
    bool
        True if the notification was sent successfully.
    """
    webhook_url = settings.SLACK_WEBHOOK_URL
    if not webhook_url:
        logger.warning("SLACK_WEBHOOK_URL not configured, skipping notification")
        return False

    blocks = _build_slack_blocks(anomaly, recommendation, pr_url)

    payload = {
        "text": (
            f"💰 Cost Optimization: {anomaly.service} — "
            f"Save ${recommendation.savings_estimate:.2f}/month"
        ),
        "blocks": blocks,
    }

    try:
        response = requests.post(
            webhook_url,
            json=payload,
            headers={"Content-Type": "application/json"},
            timeout=10,
        )
        response.raise_for_status()
        logger.info("Slack notification sent successfully")
        return True
    except requests.RequestException as exc:
        logger.error("Failed to send Slack notification: %s", exc)
        return False


def send_summary_notification(
    anomalies: list[Anomaly],
    total_savings: float,
    pr_count: int,
) -> bool:
    """
    Send a daily summary notification of all optimizations found.

    Parameters
    ----------
    anomalies : list[Anomaly]
        All anomalies detected in this run.
    total_savings : float
        Total estimated monthly savings across all anomalies.
    pr_count : int
        Number of PRs created.

    Returns
    -------
    bool
        True if the notification was sent successfully.
    """
    webhook_url = settings.SLACK_WEBHOOK_URL
    if not webhook_url:
        return False

    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "📊 Daily Cost Optimization Summary",
                "emoji": True,
            },
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Anomalies Detected:*\n{len(anomalies)}"},
                {"type": "mrkdwn", "text": f"*PRs Created:*\n{pr_count}"},
                {"type": "mrkdwn", "text": f"*Monthly Savings:*\n${total_savings:.2f}"},
                {"type": "mrkdwn", "text": f"*Annual Savings:*\n${total_savings * 12:.2f}"},
            ],
        },
    ]

    if anomalies:
        # Top anomalies by cost
        top = sorted(anomalies, key=lambda a: a.current_cost, reverse=True)[:5]
        summary_lines = [
            f"• {a.service} ({a.issue_type.value}): ${a.current_cost:.2f}/mo"
            for a in top
        ]
        blocks.append(
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Top Anomalies:*\n" + "\n".join(summary_lines),
                },
            }
        )

    payload = {"text": f"📊 Daily Summary: {len(anomalies)} anomalies, ${total_savings:.2f}/mo savings", "blocks": blocks}

    try:
        response = requests.post(webhook_url, json=payload, timeout=10)
        response.raise_for_status()
        logger.info("Summary notification sent")
        return True
    except requests.RequestException as exc:
        logger.error("Failed to send summary notification: %s", exc)
        return False
