"""
Slack notification sender for Cloud Cost Optimizer.

Posts structured messages to a Slack incoming webhook with details about
detected anomalies, recommended actions, savings estimates, and PR links.

Usage
-----
    from actions.slack_notify import send_notification
    send_notification(anomaly, recommendation, pr_url)
"""

from __future__ import annotations

import json
import logging

import requests

from config.settings import settings
from detect.models import Anomaly, Recommendation

logger = logging.getLogger(__name__)


# ──────────────────────────────────────────────────────────────────────────────
# Slack Message Formatting
# ──────────────────────────────────────────────────────────────────────────────

_RISK_EMOJI = {
    "low": "🟢",
    "medium": "🟡",
    "high": "🔴",
}

_ISSUE_EMOJI = {
    "cost_spike": "📈",
    "idle_resource": "😴",
    "overprovisioned": "🐘",
    "stopped_but_billed": "⏸️",
    "waste_pattern": "🗑️",
}


def _build_slack_blocks(
    anomaly: Anomaly,
    recommendation: Recommendation,
    pr_url: str,
) -> list[dict]:
    """
    Build Slack Block Kit blocks for a rich notification message.
    """
    issue_emoji = _ISSUE_EMOJI.get(anomaly.issue_type.value, "⚠️")
    risk_emoji = _RISK_EMOJI.get(recommendation.risk_level.value, "⚪")

    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"💰 Cost Optimization Detected — {anomaly.service}",
                "emoji": True,
            },
        },
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"*Service:*\n{anomaly.service}",
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Issue Type:*\n{issue_emoji} {anomaly.issue_type.value}",
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Current Cost:*\n${anomaly.current_cost:.2f}/mo",
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Waste Score:*\n{anomaly.waste_score}/100",
                },
            ],
        },
        {"type": "divider"},
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"*Root Cause:*\n{recommendation.root_cause[:300]}\n\n"
                    f"*Estimated Savings:* 💵 *${recommendation.savings_estimate:.2f}/month* "
                    f"(${recommendation.savings_estimate * 12:.2f}/year)\n\n"
                    f"*Risk Level:* {risk_emoji} {recommendation.risk_level.value.upper()}"
                ),
            },
        },
    ]

    # Add resource details if available
    if anomaly.resource_id:
        blocks.append(
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Resource:* `{anomaly.resource_id}` | *Region:* {anomaly.region or 'N/A'}",
                },
            }
        )

    # Add actions
    if recommendation.actions:
        actions_text = "\n".join(
            f"• {action}" for action in recommendation.actions[:5]
        )
        blocks.append(
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Recommended Actions:*\n{actions_text}",
                },
            }
        )

    # Add PR link button
    if pr_url:
        blocks.extend([
            {"type": "divider"},
            {
                "type": "actions",
                "elements": [
                    {
                        "type": "button",
                        "text": {
                            "type": "plain_text",
                            "text": "📋 Review Pull Request",
                            "emoji": True,
                        },
                        "url": pr_url,
                        "style": "primary",
                    },
                ],
            },
        ])

    # Footer
    blocks.append(
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": "🤖 Auto-generated by *Cloud Cost Optimizer* | "
                    f"Confidence: {recommendation.confidence:.0%}",
                },
            ],
        }
    )

    return blocks


# ──────────────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────────────


def send_notification(
    anomaly: Anomaly,
    recommendation: Recommendation,
    pr_url: str = "",
) -> bool:
    """(MOCKED FOR DEMO VERSION)"""
    logger.info("Mock: Sending Slack notification for %s", anomaly.service)
    return True

def send_summary_notification(
    anomalies: list[Anomaly],
    total_savings: float,
    pr_count: int,
) -> bool:
    """(MOCKED FOR DEMO VERSION)"""
    logger.info("Mock: Sending Slack summary: %d anomalies, $%.2f savings", len(anomalies), total_savings)
    return True
