# ─────────────────────────────────────────────────────────────────────────────
# EC2 Right-Sizing Terraform Module
#
# Downsizes an overprovisioned EC2 instance by changing its instance type.
# Generated by Cloud Cost Optimizer as a sample/template module.
# ─────────────────────────────────────────────────────────────────────────────

variable "instance_id" {
  description = "The EC2 instance ID to right-size"
  type        = string
}

variable "current_instance_type" {
  description = "Current instance type (for documentation)"
  type        = string
  default     = "m5.2xlarge"
}

variable "target_instance_type" {
  description = "Target (smaller) instance type"
  type        = string
  default     = "m5.large"
}

variable "environment" {
  description = "Environment tag (prod, staging, dev)"
  type        = string
  default     = "prod"
}

variable "cost_center" {
  description = "Cost center for chargeback tracking"
  type        = string
  default     = "engineering"
}

# ─────────────────────────────────────────────────────────────────────────────
# Data source: look up the existing instance
# ─────────────────────────────────────────────────────────────────────────────

data "aws_instance" "target" {
  instance_id = var.instance_id
}

# ─────────────────────────────────────────────────────────────────────────────
# Right-sized instance (replace the existing one)
# ─────────────────────────────────────────────────────────────────────────────

resource "aws_instance" "rightsized" {
  ami           = data.aws_instance.target.ami
  instance_type = var.target_instance_type
  subnet_id     = data.aws_instance.target.subnet_id

  vpc_security_group_ids = data.aws_instance.target.vpc_security_group_ids

  root_block_device {
    volume_size = data.aws_instance.target.root_block_device[0].volume_size
    volume_type = data.aws_instance.target.root_block_device[0].volume_type
    encrypted   = true
  }

  tags = merge(
    data.aws_instance.target.tags,
    {
      "Name"                = "${data.aws_instance.target.tags["Name"]}-rightsized"
      "cost-optimizer"      = "rightsized"
      "previous-type"       = var.current_instance_type
      "environment"         = var.environment
      "cost-center"         = var.cost_center
    }
  )

  lifecycle {
    create_before_destroy = true
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# Outputs
# ─────────────────────────────────────────────────────────────────────────────

output "new_instance_id" {
  description = "ID of the right-sized instance"
  value       = aws_instance.rightsized.id
}

output "new_instance_type" {
  description = "Instance type of the right-sized instance"
  value       = aws_instance.rightsized.instance_type
}

output "estimated_monthly_savings" {
  description = "Estimated monthly savings (manual calculation needed)"
  value       = "Review pricing for ${var.current_instance_type} → ${var.target_instance_type}"
}
